import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';

const page = readFileSync(new URL('./titan-black.html', import.meta.url), 'utf8');
const approvalLock = JSON.parse(readFileSync(new URL('./titan-black/.internal/content-approval-lock.json', import.meta.url), 'utf8'));

assert.equal(approvalLock.status, 'LOCKED', 'keeps the confirmed reviewer and Mazda case under an internal approval lock');
assert.equal(approvalLock.content_snapshot.path, 'auto365/titan-black.html', 'binds the approval lock to the Titan page');
const approvedMazdaAsset = readFileSync(new URL('./titan-black/hinh/titan-back-5.webp', import.meta.url));
assert.equal(createHash('sha256').update(approvedMazdaAsset).digest('hex'), approvalLock.approved_scope[1].media.sha256, 'detects any change to the approved Mazda case asset');

assert.match(page, /<meta content="noindex,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1" name="robots"\/>/, 'keeps the GitHub Pages preview out of search indexes while allowing link discovery');
assert.match(page, /<link href="https:\/\/manhcuong365group\.github\.io\/preview-365group\/titan-black\.html" rel="canonical"\/>/, 'sets the preview canonical to its exact URL');
assert.match(page, /property="og:url"/, 'provides a share URL for the preview');
assert.match(page, /property="og:image"/, 'provides a share image for the preview');
assert.doesNotMatch(page, /content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1" name="robots"/, 'does not conflict with the preview noindex directive');
assert.doesNotMatch(page, /"offers"\s*:\s*\{\s*"@type"\s*:\s*"Offer"/, 'does not publish a formal Offer while the displayed price remains a reference amount');
assert.doesNotMatch(page, /href="#tb-nearby"/, 'does not link visitors to the removed nearby-branch block');
assert.match(page, /href="https:\/\/auto365\.vn\/chi-nhanh"[^>]*>Tìm điểm lắp gần tôi<\/a>[\s\S]*?href="https:\/\/auto365\.vn\/chi-nhanh"[^>]*>Xem chi nhánh<\/a>/, 'sends both branch actions to the active Auto365 branch directory');
assert.match(page, /#tb-product \.tb-hero__grid\{[\s\S]*?align-items:stretch;[\s\S]*?#tb-product \.tb-hero__content\{[\s\S]*?align-self:stretch;/, 'keeps the desktop hero content card the same height as its image');
assert.match(page, /#tb-product \.tb-buy-grid \{[\s\S]*?align-items:stretch;/, 'keeps the quick-information card level with the consultation form on desktop');
assert.match(page, /<form action="\/api\/leads\/lighting" class="tb-checker tb-surface" id="tb-fit-form" method="post">/, 'sends the main consultation form to the production lighting lead endpoint');
assert.match(page, /<form action="\/api\/leads\/lighting" class="tb-faq__form" id="tb-faq-form" method="post">/, 'sends the FAQ consultation form to the production lighting lead endpoint');
assert.match(page, /fetch\(form\.action,\s*\{[\s\S]*?method: "POST"[\s\S]*?body:data[\s\S]*?X-Idempotency-Key/, 'posts both forms to the lead endpoint with an idempotency key');
assert.match(page, /data\.set\("vehicle_year_version"[\s\S]*?data\.set\("lens_variant", activeVariant\)[\s\S]*?!response\.ok\s*\|\|\s*!payload\.lead_id/, 'includes vehicle year/version and selected lens while confirming a real lead ID before success');
assert.match(page, /CA LẮP THỰC TẾ[\s\S]*?Mazda 3 nâng cấp Bi LED X-Light Titan Black 2026 tại Auto365\.vn – Trụ Sở Chính/, 'presents the verified Mazda 3 installation in the AES-style case format');
assert.match(page, /Nguyễn Quang Đạo[\s\S]*?Đã kiểm duyệt nội dung kỹ thuật của bài Titan Black 2026/, 'records the confirmed technical review');
assert.doesNotMatch(page, /dịu mắt|đi mưa hoặc sương mù/i, 'removes unsupported lighting-performance claims');
assert.doesNotMatch(page, /Cos 5200K · Pha 3000K|40 W\/đèn|50 W\/đèn|60 W\/đèn|65 W\/đèn|12–24 V|\+10 W|\+15 W/, 'keeps thermal-color and legacy-comparison data within the verified wording');
assert.match(page, /Cos 5200K · tâm Pha 3000K[\s\S]*?<tr><td>Công suất Cos<\/td><td>40 W<\/td><td>60 W<\/td><td>~70 W\/đèn<\/td><\/tr>[\s\S]*?<tr><td>Điện áp<\/td><td>12 V và 24 V<\/td>/, 'uses consistent thermal-color wording and preserves legacy data units as published');
assert.doesNotMatch(page, /Cos\/Pha rõ hơn|phát huy hiệu quả khi đi đêm|dịu hơn bản 2021|cải thiện khả năng chiếu sáng khi di chuyển ban đêm/i, 'removes unsupported comparative or outcome claims');
assert.doesNotMatch(page, /id="review"|id="production-data"|id="tb-nearby"|id="tb-technical-review"/, 'removes hidden internal, review and production-only sections from public HTML');
assert.match(page, /id="tuong-thich"/, 'requires a public compatibility section');
assert.match(page, /Lens tròn: 130 × 80 × 80 mm/, 'requires the round-lens dimensions');
assert.match(page, /Lens vuông: 130 × 80 × 65 mm/, 'requires the square-lens dimensions');
assert.match(page, /CANBUS\/decoder.*báo riêng|báo riêng.*CANBUS\/decoder/s, 'requires CANBUS pricing guidance');
assert.match(page, /hình ảnh.*minh họa|minh họa.*hiệu quả thực tế/is, 'requires a light-image disclaimer');
assert.match(page, /không cam kết kết quả đăng kiểm/i, 'requires a registration disclaimer');
assert.match(page, /article\.tb-surface > figure\.tb-media img\{width:76%!important;height:76%!important;object-fit:contain!important\}/, 'requires an inline-style override that keeps the whole H4 accessory visible');
assert.match(page, /\.tb-feature:nth-child\(1\) figure\{[^}]*background-image:url\('titan-black\/hinh\/titan-back-2\.webp'\)[^}]*\}/, 'requires the supplied two-version image for the lens block');
assert.match(page, /\.tb-feature:nth-child\(1\) figure\{[^}]*background-color:#087bd0/, 'requires a blue surround instead of black side bars');
assert.match(page, /\.tb-feature:nth-child\(1\) figure\{[^}]*background-size:100% 100%/, 'requires the supplied lens image to fill its matching frame');
assert.match(page, /\.tb-feature:nth-child\(2\) figure\{[^}]*aspect-ratio:16 \/ 9[^}]*background-size:100% 100%/, 'requires the cooling image to fill its matching frame');
assert.match(page, /<form action="\/api\/leads\/lighting" class="tb-faq__form" id="tb-faq-form" method="post">[\s\S]*Nhận tư vấn miễn phí[\s\S]*name="year"[\s\S]*name="need"[\s\S]*Chính sách bảo mật/, 'requires the production lead form in the FAQ column');
assert.match(page, /@media \(max-width:480px\)\{#tb-product \.tb-faq__form-grid\{grid-template-columns:repeat\(2,minmax\(0,1fr\)\);gap:10px 8px\}\}/, 'keeps FAQ consultation fields in compact paired mobile rows');
assert.match(page, /querySelectorAll\("#tb-fit-form,#tb-faq-form"\)[\s\S]*?fetch\(form\.action,\s*\{[\s\S]*?method: "POST"[\s\S]*?body:data/, 'sends both consultation forms to the production lead API');
assert.match(page, /<span class="tb-faq__label-text">Họ và tên <b aria-hidden="true">\*<\/b><\/span><input name="name"/, 'keeps the name required marker inline with its label');
assert.match(page, /<span class="tb-faq__label-text">Số điện thoại <b aria-hidden="true">\*<\/b><\/span><input inputmode="tel" name="phone"/, 'keeps the phone required marker inline with its label');
assert.match(page, /class="tb-faq__form-actions"[\s\S]*?<span>Nhắn Zalo<\/span>[\s\S]*?Hotline 0365 365 911[\s\S]*?Tìm chi nhánh/, 'adds concise Zalo, hotline and branch actions beneath the consultation request');
assert.match(page, /\.tb-faq__form-actions\s*\{\s*display:grid;grid-template-columns:1\.5fr 1fr 1\.2fr;gap:8px/, 'keeps the three FAQ contact actions on one row where space permits');
assert.match(page, /\.tb-faq__form-actions \.tb-btn:first-child\s*\{\s*grid-column:auto;background:#087ff0/, 'styles the Zalo action blue without spanning the row');
assert.match(page, /class="tb-btn tb-btn--zalo"[^>]*href="https:\/\/zalo\.me\/3622666363345050913"[^>]*><svg[^>]*class="tb-faq__action-icon"/, 'marks the FAQ Zalo action for its dedicated blue treatment and visible icon');
assert.match(page, /\.tb-faq__action-icon \{ display:block;flex:0 0 auto;width:16px;height:16px/, 'shows compact action icons at every viewport width');
assert.match(page, /@media \(max-width:480px\)\{[\s\S]*?\.tb-faq__form-actions \.tb-btn span\{display:none\}/, 'switches FAQ contact actions to compact icon-only controls on narrow phones');
assert.match(page, /@media \(min-width:481px\)\{[\s\S]*?\.tb-faq__form-actions \{ display:grid;grid-template-columns:repeat\(3,minmax\(0,1fr\)\); \}[\s\S]*?\.tb-faq__form-actions \.tb-btn span\{display:inline\}[\s\S]*?\.tb-faq__form-actions \.tb-btn--zalo\{background:#e92531;border-color:#e92531\}/, 'uses evenly stretched text contact actions on web');
for (const redundantCopy of [
  'So sánh các thông số công bố của Titan Black 2021, 2.0 và phiên bản 2026.',
  'Auto365 chỉ xác nhận phương án sau khi kiểm tra cụm đèn và hệ điện thực tế.',
  'Quy trình 7 bước giúp thống nhất phương án, thi công và kiểm tra trước khi bàn giao.',
  'Nội dung kỹ thuật của Bi LED Titan Black 2026 được đối chiếu với tài liệu sản phẩm. Phương án lắp đặt cần được kiểm tra theo cụm đèn, không gian lắp và hệ điện của từng xe.',
  'Thông tin cần biết để chọn đúng phiên bản và xác nhận phương án theo xe thực tế.'
]) assert.doesNotMatch(page, new RegExp(redundantCopy.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')), `removes redundant copy: ${redundantCopy}`);
assert.doesNotMatch(page, /content:"FIT CHECK"/, 'removes the decorative fit-check label');
assert.doesNotMatch(page, /content:"VEHICLE FIT"/, 'removes the decorative vehicle-fit label');
assert.match(page, /<div class="tb-spec-list">[\s\S]*Điện áp[\s\S]*Bảo hành[\s\S]*<\/div>\s*<div>[\s\S]*Nhiệt màu[\s\S]*Tuổi thọ công bố[\s\S]*<\/div>\s*<\/div>/, 'balances the specification list into two equal columns');
assert.match(page, /#tb-product #thong-so \.tb-spec-list\{grid-template-columns:1fr;gap:0\}/, 'stacks the balanced specifications into one readable column on mobile');
assert.match(page, /#tb-product #so-sanh \.tb-compare__media\{grid-template-columns:1fr\}/, 'stacks the comparison visual and upgrade summary on mobile');
assert.match(page, /@media \(max-width:480px\)\{#tb-product \.tb-faq__form-grid\{grid-template-columns:repeat\(2,minmax\(0,1fr\)\);gap:10px 8px\}\}/, 'keeps consultation form fields in paired rows on narrow phones');
assert.doesNotMatch(page, /#tb-product \.tb-light-shared\{[^}]*max-width:1120px[^}]*}/, 'keeps the shared lighting visual at its original full-width treatment');
assert.match(page, /<div class="tb-price-line">\s*<div class="tb-price">6\.500\.000đ<\/div>\s*<span class="tb-price-vat">\/ cặp \(2 đèn\) · chưa VAT<\/span>[\s\S]*?Công lắp, pát, giắc, dây, CANBUS\/decoder/, 'states the unit, VAT and vehicle-specific installation costs beside the top price');
const heroTrust = page.match(/<div aria-label="Điểm nổi bật Titan Black 2026" class="tb-hero-trust">([\s\S]*?)<\/div>\s*<\/div>\s*<section/)?.[1] ?? '';
assert.doesNotMatch(heroTrust, /<span>0[123]<\/span>/, 'removes the 01, 02 and 03 labels from the hero fact cards');
assert.match(page, /\.tb-hero-trust > div\{[\s\S]*?grid-template-columns:1fr;[\s\S]*?grid-template-areas:"v" "l"/, 'realigns the hero fact cards after removing their number labels');
assert.match(page, /<div class="tb-hero-commerce__main">\s*<a class="tb-btn tb-btn--dark"[\s\S]*?Nhắn Zalo tư vấn[\s\S]*?<a class="tb-btn tb-btn--primary" href="#kiem-tra-xe">Kiểm tra xe có lắp được không<\/a>/, 'places the vehicle check action beside Zalo consultation');
assert.match(page, /class="tb-checker__actions"[\s\S]*?Nhận tư vấn phương án lắp[\s\S]*?Nhắn Zalo[\s\S]*?Hotline 0365 365 911/, 'adds Zalo and hotline actions beside the top consultation form submission');
assert.match(page, /\.tb-checker__actions \{ display:grid;grid-template-columns:1\.35fr 1fr 1\.2fr/, 'keeps the three top consultation actions aligned on desktop');
assert.match(page, /@media \(max-width:767\.98px\) \{[\s\S]*?\.tb-checker__grid \{ grid-template-columns:repeat\(2,minmax\(0,1fr\)\);gap:8px;/, 'keeps the top vehicle consultation fields in two compact mobile columns');
assert.match(page, /class="tb-checker__grid">[\s\S]*?name="name"[\s\S]*?name="phone"[\s\S]*?name="area"[\s\S]*?name="brand"[\s\S]*?name="model"[\s\S]*?name="year"[\s\S]*?name="need"[\s\S]*?<\/div>\s*<label class="tb-checker__consent">[\s\S]*?<div class="tb-checker__actions">/, 'keeps vehicle model year/version, paired mobile rows and consent before the consultation actions');
assert.match(page, /\.tb-checker__consent \{ display:flex!important;width:100%[\s\S]*?\.tb-checker__consent input \{ width:16px!important;min-width:16px!important;height:16px!important;min-height:16px!important;flex:0 0 16px!important/, 'keeps the privacy checkbox compact and its consent copy on the same full-width row');
assert.match(page, /@media\(max-width:767\.98px\)\{[\s\S]*?#thiet-ke > \.tb-shell > article\.tb-surface\{grid-template-columns:1fr!important;gap:0!important\}/, 'stacks the H4 accessory image above its content on mobile');
assert.match(page, /\.tb-light-shared\{aspect-ratio:auto;background:#fff\}[\s\S]*?\.tb-light-shared img\{display:block;width:100%;height:auto;object-fit:contain\}/, 'shows the full Cos/Pha illustration without cropping');
assert.match(page, /#tb-product h2\{font-size:clamp\(22px,2vw,28px\)!important\}[\s\S]*?#tb-product h3\{font-size:clamp\(17px,1\.35vw,21px\)!important\}/, 'keeps secondary headings compact');
assert.doesNotMatch(page, /Hình ảnh dùng để minh họa cấu hình Cos\/Pha theo tư liệu sản phẩm; hiệu quả thực tế phụ thuộc cụm đèn, cách căn chỉnh, mặt đường, thời tiết và điều kiện sử dụng của từng xe\./, 'removes the lighting-image disclaimer requested by the user');
assert.doesNotMatch(page, /<p class="tb-eyebrow">Hiệu suất ánh sáng<\/p>/, 'removes the lighting-section eyebrow requested by the user');
assert.doesNotMatch(page, /Công lắp và vật tư phát sinh xác nhận theo xe/, 'removes the extra installation-cost note below the hero price');
assert.match(page, /<h3 style="margin-top:8px">Nhôm \+ quạt<\/h3>[\s\S]*Quạt tản nhiệt 45 mm hỗ trợ lưu thông khí phía sau cụm đèn/, 'balances the cooling card with its 45 mm fan detail');
assert.match(page, /\.tb-light-shared\{flex:1 1 600px\}/, 'keeps the lighting visual beside the Cos and Pha guidance when space permits');
assert.match(page, /<div class="tb-light-layout">\s*<figure class="tb-light-shared">[\s\S]*?<div class="tb-light-copy-grid">[\s\S]*?Cos 5200K:[\s\S]*?Tâm Pha 3000K:[\s\S]*?<\/div>\s*<\/div>/, 'groups the light visual and stacked guidance into one layout');
const visibleLightingCopy = page.match(/<div class="tb-light-copy-grid">([\s\S]*?)<\/div>\s*<\/div>\s*<div class="tb-light-grid">/)?.[1] ?? '';
assert.doesNotMatch(visibleLightingCopy, /<p class="tb-eyebrow">Chế độ Cos<\/p>|<p class="tb-eyebrow">Chế độ Pha<\/p>/, 'removes redundant Cos and Pha mode labels');
assert.match(page, /\.tb-light-copy-grid article\{display:flex;flex-direction:column;justify-content:flex-start;position:relative;padding:24px 28px\}[\s\S]*?\.tb-light-copy-grid h3\{margin:0;font-size:clamp\(18px,1\.3vw,22px\)!important/, 'aligns compact Cos and Pha copy at the top of each card');
assert.match(page, /#tb-product \.tb-light-layout/, 'defines a responsive mobile treatment for the lighting layout');
assert.match(page, /\.tb-light-layout\{display:flex;flex-wrap:wrap;gap:18px;align-items:stretch\}/, 'uses a wrapping lighting layout that cannot overlap at zoomed viewport widths');
const updatedLightingImage = '1789026525188_9057802958140973376_9057802958140973376_24cc37fb87b116baa0436686dd1cbd07.jpg';
assert.match(page, new RegExp(`src="titan-black/hinh/${updatedLightingImage}"`), 'uses the supplied replacement lighting illustration');
assert.match(page, new RegExp(`background:#071220 url\\('titan-black/hinh/${updatedLightingImage.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}'\\) center / cover no-repeat`), 'uses the replacement image as the lighting frame fallback');
assert.ok(existsSync(new URL(`./titan-black/hinh/${updatedLightingImage}`, import.meta.url)), 'publishes the supplied replacement lighting asset');
for (const removedDescription of ['Kết hợp nhiệt màu tối ưu, hỗ trợ tầm nhìn rõ ràng trong nhiều điều kiện di chuyển.', 'Chọn hãng xe để xem các ca đã thực hiện. Các ca dưới đây sử dụng Titan Black 2.0; phương án Titan Black 2026 cần được kiểm tra theo cụm đèn và hệ điện thực tế.']) assert.doesNotMatch(page, new RegExp(removedDescription.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')), `removes requested supporting copy: ${removedDescription}`);
assert.match(page, /const specifications = root\.querySelector\("#thong-so"\);[\s\S]*?if \(specifications && comparison\) comparison\.before\(specifications\);/, 'places the full technical specifications before the generation comparison');
const whyBuySection = page.match(/<section class="tb-section tb-why-buy" id="tb-why-buy">([\s\S]*?)<\/section>/)?.[1] ?? '';
for (const caseBacklink of ['do-den-bi-led-titan-black-20-tai-thanh-hoa', 'do-den-toyota-fortuner-moi-nhat-nam-2024', 'o-den-hyundai-i10']) assert.doesNotMatch(whyBuySection, new RegExp(`href="https://auto365\\.vn/${caseBacklink}"`), `removes actual-installation case backlinks from editorial copy: ${caseBacklink}`);
assert.doesNotMatch(page, /<div class="tb-related-grid">/, 'removes the separate related-articles card grid');
assert.match(page, /Tham khảo các xe đã lắp đèn Titan Black tại Auto365/, 'uses an AES-style actual-installation library heading');
assert.doesNotMatch(page, /#tb-product #case-xe\s*\{display:none/, 'keeps the actual-installation library visible');
assert.match(page, /id="tb-trusted-address"[\s\S]*?Địa chỉ lắp Titan Black 2026 uy tín[\s\S]*?91 điểm · 33 tỉnh thành[\s\S]*?Miền Bắc[\s\S]*?Miền Trung[\s\S]*?Miền Nam/, 'combines the trusted Titan Black address and national Auto365 coverage in one block');
assert.match(page, /Địa chỉ lắp Titan Black 2026 uy tín[\s\S]*?tb-trusted-address__points[\s\S]*?tb-trusted-address__coverage[\s\S]*?Nhắn Zalo[\s\S]*?Hotline 0365 365 911/, 'places installation checks on the left and contact actions on the right');
const trustedAddress = page.match(/<section class="tb-section" id="tb-trusted-address">([\s\S]*?)<\/section>/)?.[1] ?? '';
assert.doesNotMatch(trustedAddress, /<p class="tb-eyebrow">Phủ sóng toàn quốc<\/p>/, 'removes the redundant nationwide-coverage eyebrow from the visible address block');
assert.match(page, /@media\(min-width:768px\)\{#tb-product \.tb-trusted-address__coverage h3\{margin-bottom:48px\}\}/, 'aligns the coverage row with the installation-check rows on desktop');
assert.match(page, /#tb-product #tb-nearby\{display:none\}/, 'removes the separate nearby-branch block after it is consolidated into the Auto365 introduction');
assert.match(page, /id="case-xe"[\s\S]*?id="lap-dat"[\s\S]*?id="tb-trusted-address"/, 'orders cases, installation process and consolidated Auto365 information in sequence');
assert.match(page, /data-install-filter="all"[\s\S]*?data-install-filter="toyota"[\s\S]*?data-install-filter="kia"/, 'provides brand filters for the actual-installation library');
assert.match(page, /class="tb-install-grid"[\s\S]*?Toyota Camry[\s\S]*?Kia Morning[\s\S]*?Tổng hợp các mẫu xe/, 'shows three real Titan Black case cards');
assert.match(page, /#case-xe \.tb-install-grid\{display:flex;gap:12px;overflow-x:auto;[\s\S]*?scroll-snap-type:x proximity/, 'makes actual installation cases horizontally scrollable on mobile');
for (const caseUrl of ['toyota-nang-bi-led-titan-black-2', 'kia-morning-titan-black-2', 'do-den-bi-led-titan-black-20-tai-thanh-hoa']) assert.match(page, new RegExp(`href="https://auto365\\.vn/${caseUrl}"`), `links the actual Titan case: ${caseUrl}`);
assert.match(page, /installFilters\.forEach[\s\S]*?dataset\.installBrand/, 'makes the actual-installation brand filters functional');
assert.match(page, /id="tb-actual-2026"[\s\S]*?class="tb-actual-2026__grid"[\s\S]*?titan-black\/hinh\/titan-back-5\.webp[\s\S]*?figcaption>Hình ảnh ca Mazda 3 nâng cấp Bi LED X-Light Titan Black tại Auto365 Trụ Sở Chính\.<\/figcaption>/, 'presents the supplied Mazda 3 image in a dedicated left-side feature panel');
assert.ok(existsSync(new URL('./titan-black/hinh/titan-back-5.webp', import.meta.url)), 'publishes the supplied Mazda 3 image asset with the page');
assert.match(page, /id="tb-actual-2026"[\s\S]*?<h2>Mazda 3 nâng cấp Bi LED X-Light Titan Black 2026 tại Auto365\.vn – Trụ Sở Chính<\/h2>[\s\S]*?class="tb-actual-2026__note"/, 'identifies the Mazda 3 installation as Titan Black 2026 at Auto365.vn headquarters');
assert.doesNotMatch(page, /class="tb-actual-2026__badge">Hình thực tế<\/span>/, 'removes the redundant actual-image badge');
assert.match(page, /const pageFlow = \[[\s\S]*?"kiem-tra-xe"[\s\S]*?"video-teaser"[\s\S]*?"nhu-cau"[\s\S]*?"thong-so"[\s\S]*?"anh-sang"[\s\S]*?"thiet-ke"[\s\S]*?"tuong-thich"[\s\S]*?"so-sanh"[\s\S]*?"tb-fit-summary"[\s\S]*?"tb-consult-cta"[\s\S]*?"tb-actual-2026"[\s\S]*?"case-xe"[\s\S]*?"lap-dat"[\s\S]*?"tb-trusted-address"[\s\S]*?"faq"[\s\S]*?"trust"/, 'places editorial and technical review at the end of the article');
assert.match(page, /id="trust"[\s\S]*?Nguồn &amp; kiểm duyệt[\s\S]*?Biên Tập Viên Auto365[\s\S]*?Nguyễn Quang Đạo/, 'shows the existing editor and technical reviewer identities');
assert.doesNotMatch(page, /Không chỉ để “đẹp SEO”: người mua cần biết số liệu đến từ đâu, ai chịu trách nhiệm cập nhật và khi nào thông tin thay đổi\./, 'removes the unapproved trust-section supporting sentence');
for (const productionPlaceholder of ['[ĐÃ/CHƯA] VAT', '[0365 xxx xxx]', '[Toyota Fortuner / mẫu xe] [202x]', '[Tên khách / ẩn danh]', '[4.x]/5', '[xxx.xxxđ]', 'Production data checklist', 'Campaign ID', 'API/CRM endpoint']) {
  assert.doesNotMatch(page, new RegExp(productionPlaceholder.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')), `removes production placeholder from public HTML: ${productionPlaceholder}`);
}
assert.doesNotMatch(page, /Đi đêm rõ hơn, mắt bớt mỏi/, 'removes the unsupported eye-fatigue claim');
assert.doesNotMatch(page, /id="tb-final-cta"/, 'removes the dark final consultation block requested by the user');
assert.match(page, /pageFlow\.forEach[\s\S]*?root\.append\(section\);[\s\S]*?const footer = root\.querySelector\("\.tb-footer"\);[\s\S]*?if \(footer\) root\.append\(footer\);/, 'moves the footer after the ordered page flow instead of leaving a blank gap after the hero');
assert.match(page, /const anchoredSection = location\.hash \? root\.querySelector\(location\.hash\) : null;[\s\S]*?if \(anchoredSection\) requestAnimationFrame\(\(\) => anchoredSection\.scrollIntoView\(\)\);/, 'restores hash-link scrolling after sections are reordered');
assert.match(page, /#tb-product #tb-fit-summary\{display:block\}/, 'keeps the approved "phù hợp khi nào" section visible');
assert.match(page, /#tb-product #evidence\{display:none\}/, 'hides the extra technical-evidence section that is outside the approved flow');
assert.match(page, /@media\(max-width:767\.98px\)\{[\s\S]*?--tb-mobile-gutter:clamp\(14px,4vw,22px\)/, 'defines a fluid mobile gutter from the page design tokens');
assert.match(page, /@media\(max-width:767\.98px\)\{[\s\S]*?\.tb-light-layout\{display:grid;grid-template-columns:1fr/, 'turns the flex-based light layout into a true one-column mobile layout');
assert.match(page, /@media\(max-width:1199\.98px\) and \(min-width:768px\)\{[\s\S]*?\.tb-light-layout\{display:grid;grid-template-columns:minmax\(0,1fr\)/, 'uses a true stacked layout for the light visual at intermediate mobile and tablet widths');
assert.match(page, /@media\(max-width:767\.98px\)\{[\s\S]*?\.tb-actual-2026\{max-width:none/, 'removes the desktop image width cap on mobile');
assert.match(page, /@media\(max-width:767\.98px\)\{[\s\S]*?\.tb-actual-2026__grid\{grid-template-columns:1fr/, 'stacks the Mazda 3 feature image and summary on mobile');
assert.match(page, /@media\(max-width:767\.98px\)\{[\s\S]*?\.tb-section-head h2\{font-size:clamp\(/, 'uses fluid heading type on mobile instead of fixed pixel sizes');
assert.match(page, /id="nhu-cau"[\s\S]*?<h2 style="margin-top:8px">Titan Black 2026 giải quyết vấn đề gì\?<\/h2>/, 'preserves the previously approved needs-section copy');
assert.doesNotMatch(page, /Không nên quyết định chỉ dựa vào công suất\. Hãy bắt đầu từ tình huống lái xe và cấu hình cụm đèn hiện tại\./, 'removes the unapproved needs-section supporting sentence');
assert.match(page, /#tb-product \.tb-hero \{\s*padding-block:18px 28px;\s*background:#fff;/, 'uses a flat white hero background');
assert.match(page, /#tb-product \.tb-trusted-address\{[^}]*background:#fff\}/, 'uses a flat white trusted-address background');
assert.match(page, /Tâm Pha 3000K cần được căn chỉnh theo từng cụm đèn trước khi bàn giao\./, 'uses evidence-based copy for the Pha decision card');
assert.doesNotMatch(page, /Titan Black 2026 công bố tâm Pha 3000K; hiệu quả thực tế còn phụ thuộc căn chỉnh và cụm đèn\./, 'removes the short Pha copy that leaves the card visually unbalanced');
assert.match(page, /\.tb-decision-card\{padding:var\(--tb-card-pad\);display:flex;flex-direction:column\}/, 'makes decision cards equal-height flex columns');
assert.match(page, /\.tb-decision-card__tag\{display:inline-flex;margin-top:auto;padding:5px 8px/, 'keeps decision-card tags aligned despite different copy lengths');
const decisionCards = page.match(/<div class="tb-decision-grid">([\s\S]*?)<\/div>\s*<\/section>/)?.[1] ?? '';
assert.doesNotMatch(decisionCards, /<span class="tb-decision-card__icon">0[123]<\/span>/, 'removes the 01, 02 and 03 labels from the decision cards');
assert.match(page, /@media\(max-width:1023\.98px\)\{[\s\S]*?\.tb-decision-grid\{display:flex;grid-template-columns:none;overflow-x:auto;scroll-snap-type:x proximity[\s\S]*?\.tb-decision-card\{flex:0 0 min\(82vw,360px\);scroll-snap-align:start/, 'turns decision cards into a horizontal swipe row on mobile and tablet widths');
assert.doesNotMatch(page, /id="tb-why-buy"/, 'removes the hidden editorial section from public HTML');
assert.match(page, /#tb-product #tb-why-buy\{display:none\}/, 'keeps the unapproved editorial section out of the published layout');
assert.match(page, /#tb-product #tb-fit-summary,#tb-product #gia-bao-gom,#tb-product #tb-booking,#tb-product #tb-handover,#tb-product #review,#tb-product #production-data,#tb-product #tb-nearby,#tb-product #tb-technical-review,#tb-product #bai-lien-quan\{display:none\}/, 'hides every section outside the user-approved landing-page flow except the verified reviewer block');
assert.doesNotMatch(page, /#tb-product #nhu-cau\{display:none\}/, 'keeps the approved needs section visible');
assert.match(page, /#tb-product #faq \.tb-faq\{grid-template-columns:repeat\(2,minmax\(0,1fr\)\);align-items:stretch\}[\s\S]*?#tb-product #faq \.tb-faq\{align-items:start\}/, 'keeps FAQ columns top-aligned so answers can grow naturally');
assert.match(page, /id="faq"[\s\S]*?class="tb-shell tb-faq"[\s\S]*?tb-faq__form[\s\S]*?class="tb-faq__questions"[\s\S]*?<h2>Câu hỏi thường gặp<\/h2>[\s\S]*?tb-faq-list/, 'places the FAQ heading above the right-hand question column');
assert.match(page, /#tb-product #faq \.tb-faq > div:first-child,#tb-product #faq \.tb-faq__questions\{display:block\}/, 'keeps the form and question column independent of each other');
assert.match(page, /#tb-product \.tb-faq details\{\s*width:100%;\s*margin:0;\s*padding:11px 16px;/, 'keeps FAQ questions compact and aligned to the full FAQ column');
assert.match(page, /#tb-product #faq \.tb-faq__questions \.tb-faq-list\{height:auto;grid-auto-rows:auto;align-content:start\}/, 'keeps FAQ rows fitted to their natural content height');
assert.match(page, /#tb-product #faq \.tb-faq details:not\(\[open\]\)\{display:block;min-height:0;padding:14px 16px\}/, 'keeps closed FAQ summaries compact instead of vertically stretching them');
assert.match(page, /@media\(max-width:767\.98px\)\{[\s\S]*?#faq \.tb-faq-list\{height:auto;grid-auto-rows:auto;align-content:start\}[\s\S]*?#faq \.tb-faq details:not\(\[open\]\)\{display:block;min-height:0;padding:14px 16px\}/, 'keeps mobile FAQ rows fitted to their content instead of desktop-height stretching');
assert.match(page, /#tb-product #faq \.tb-faq-list\{overflow-anchor:none\}/, 'prevents browser scroll anchoring from moving the FAQ viewport');
assert.match(page, /querySelectorAll\("#faq details"\)\.forEach[\s\S]*?window\.scrollBy\(\{ top:summary\.getBoundingClientRect\(\)\.top - summaryTop/, 'keeps the toggled FAQ summary in place instead of jumping the viewport');
assert.match(page, /Giá tham khảo là 6\.500\.000 VNĐ\/cặp[\s\S]*?CANBUS\/decoder/, 'groups possible CANBUS costs into the price FAQ');
assert.doesNotMatch(page, /<summary>CANBUS\/decoder có tính thêm chi phí không\?<\/summary>/, 'removes the separate CANBUS FAQ to keep the columns balanced');
assert.match(page, /img\[alt="Phụ kiện đuôi vặn H4 Titan Black 2026"\]\{content:url\("titan-black\/hinh\/phu-kien-h4-bi-led-titan-black-2026\.jpg"\)/, 'uses the supplied H4 accessory image');
assert.match(page, /href="https:\/\/auto365\.vn\/bi-led-titan-black-2"/, 'keeps a contextual link to Titan Black 2.0 for generation comparison');
assert.doesNotMatch(page, /data:image\/(?:webp|png|jpe?g);base64,/, 'keeps product imagery out of inline base64 data URIs');
assert.doesNotMatch(page, /titan-inline-03\.webp|titan-inline-04\.webp/, 'removes hidden references to unavailable lighting images');
const referencedAssets = [...new Set([...page.matchAll(/titan-black\/hinh\/([A-Za-z0-9._-]+)/g)].map(match => match[1]))];
for (const imageFile of referencedAssets) {
  assert.ok(existsSync(new URL(`./titan-black/hinh/${imageFile}`, import.meta.url)), `stores every referenced product asset: ${imageFile}`);
}
